CREATE TABLE IF NOT EXISTS orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    customer_name varchar(50) NOT NULL,
    customer_phone varchar(18) NOT NULL,
    customer_email varchar(50) NOT NULL,
    amount int NOT NULL,
    delivery_address varchar(500) NOT NULL,
    delivery_date TIMESTAMP WITHOUT TIME ZONE,
    status varchar(20) NOT NULL
    );